### ISSUE TITLE
ERC 1155 like in Cairo

### ISSUE THREAD

**Issue by Th0rgal** [lfglabs-dev/erc1155_component#1]
To create the Starkurabu assets contract we will need something similar to the semi fungible `ERC1155`:  a contract which follows `ERC721` interface + allows to own multiple instances of a token. Let's create it as a component so we can reuse it.

The interface is available here: https://eips.ethereum.org/EIPS/eip-1155

Some work was started here: https://github.com/OpenZeppelin/cairo-contracts/pull/852

But it seems there has been no work on it for two weeks, we should ask Martín to make sure. If they didn't do it yet we will need to convert it to a component to make it maintainable.

**Comment by martriay** [comment]
You should track https://github.com/OpenZeppelin/cairo-contracts/pull/896.
